### PR TITLE
Update Readme, images, emojis and more

### PR DESCRIPTION
**Pull request by i-am-henri**
Hey, I added 3 images, all of these were made in Figma, the font is Poppins. I also added emojis as points in the list. 

(please tell me mistakes, it's my first PR and open-source work 😅)

### CODE REVIEW

**Comment by i-am-henri** [comment]
Oh, I made a mistake in the last point of the list. The emoji is wrong 😅

**Review by junkmasterjim — APPROVED** [review]
Thank you. Looks good. 

I will make some smaller adjustments, but I like the changes!

**Review by junkmasterjim — APPROVED** [review]

**Comment by i-am-henri** [comment]
Thank you

**Comment by junkmasterjim** [comment]
I went through it and used it for the new readme. Thank you!

**Pull request merged**
